version: '3.9'
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  namenode:
    image: 'rubenss/hadoop:latest'
    hostname: hdpmaster
    networks:
      mynetwork:
        ipv4_address: 172.20.0.100
    container_name: hdpmaster
    restart: always
    ports:
      - '8088:8088'
      - '9870:9870'
      - '9000:9000'
      - '2201:22'
    volumes:
      - 'hadoop_namenode:/hadoop/dfs/name'
  datanode1:
    image: 'rubenss/hadoop:latest'
    hostname: hdpslv1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.210
    container_name: hdpslv1
    restart: always
    ports:
      - '2202:22'
    volumes:
      - 'hadoop_datanode1:/hadoop/dfs/data'
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
  datanode2:
    image: 'rubenss/hadoop:latest'
    hostname: hdpslv2
    networks:
      mynetwork:
        ipv4_address: 172.20.0.220
    container_name: hdpslv2
    restart: always
    ports:
      - '2203:22'
    volumes:
      - 'hadoop_datanode2:/hadoop/dfs/data'
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
volumes:
  hadoop_namenode: null
  hadoop_datanode1: null
  hadoop_datanode2: null
