FROM centos:7

LABEL maintainer="Rubens Suzuqui +> rubens545.s@gmail.com"

RUN yum update -y
RUN yum upgrade -y
RUN yum install epel-release wget tar gzip -y java-1.8.0-openjdk java-1.8.0-openjdk-devel