FROM localhost:5000/hadoop-namenode_base:latest

COPY \/files/*.xml $HADOOP_HOME/etc/hadoop/*.xml
COPY \/files\workers $HADOOP_HOME/etc/hadoop/workers
COPY \/files\hadoop-env.sh $HADOOP_HOME/etc/hadoop/hadoop-env.sh
COPY \/files\log4j.properties $HADOOP_CONF_DIR/log4j.properties

#RUN bash 
#RUN su hadoop