FROM localhost:5000/base-centos7:latest

COPY \/files/*.xml /usr/local/hadoop/etc/hadoop/*.xml
COPY \/files/workers /usr/local/hadoop/etc/hadoop/workers
COPY \/files/hadoop-env.sh /usr/local/hadoop/etc/hadoop/hadoop-env.sh
COPY \/files/log4j.properties /usr/local/hadoop/etc/hadoop/log4j.properties
