name: Docker Image CI Build Deploy Docker HUB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image BASE
      run: docker build -t rubenss/hadoop:base -f images/dockerfile.centos .
    - name: Build the Docker image BASE pull
      run: docker pull rubenss/hadoop:base
    - name: Build the Docker image HADOOP
      run: docker build -t rubenss/hadoop:latest -f images/dockerfile.hadoop .
    - name: Docker Login
      run: docker login -u rubenss -p ${{ secrets.DOCKERHUB }}
    - name: Docker Push all tags
      run: docker push --all-tags rubenss/hadoop
#    - name: Docker Push latest
#      run: docker push rubenss/hadoop:latest
