name: Docker Image CI Build Deploy Docker HUB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image BASE
      run: docker build -t rubenss/hadoop:base -f images_base/dockerfile.centos .
    - name: Build the Docker image HADOOP
      run: docker build -t rubenss/hadoop:hadoop -f images_hadoop/dockerfile.hadoop . 
    - name: Build the Docker image SPARK
      run: docker build -t rubenss/hadoop:spark -f images_spark/dockerfile.spark .      
    - name: Docker Login
      run: docker login -u rubenss -p ${{ secrets.DOCKERHUB }}
    - name: Docker Push all tags
      run: docker push --all-tags rubenss/hadoop
